### ISSUE TITLE
makefile upload target missing or deprecated?

### ISSUE THREAD

**Issue by balux33** [stnolting/neorv32#193]
Hi!
Previously i used the make upload command to upload program via uart and bootloader 
and generally worked well.
Newer versions no longer include the upload target.
Is it just left out or has it become obsolete?
if so, what is the new way to upload via uart?

**Comment by stnolting** [comment]
Hey!
Yes, that feature was deprecated because it was never really reliable.

The standard way to upload executables via UART is to use the bootloader console in a terminal program. Right now, there is no default option to upload executables directly from the shell. However, the underlying script is still available [`sw/image_gen/uart_upload.sh`](https://github.com/stnolting/neorv32/blob/master/sw/image_gen/uart_upload.sh) but I have not tested that with never versions.

Recently, I stumbled across this: https://github.com/islandcontroller/neorv32load I have not tried that myself but it looks handy!

**Comment by stnolting** [comment]
@balux33 
If you have no further questions this can be closed, right?
