### ISSUE TITLE
SPI Mode 0, MISO Data is sampled one wrong edge 

### ISSUE THREAD

**Issue by andkae** [stnolting/neorv32#371]
Hi Stephan,

at the moment i do some tests with the SPI module 9c653245. The SPI is configured as follows:

```c
/* setup SPI */
neorv32_spi_disable();
    // neorv32_spi_setup(uint8_t prsc, uint8_t clk_phase, uint8_t clk_polarity, uint8_t data_size)
neorv32_spi_setup(0, 0, 0, 0);  // spi mode 0, 8bit
neorv32_spi_highspeed_enable(); // running at half of the processor clock
neorv32_spi_enable();

/* perform SPI write */
neorv32_spi_cs_en(0);   // lines are LOW when activated.
	// READ IST
neorv32_spi_trans(0x3);
	// 24Bit ADR
neorv32_spi_trans(0x0);
neorv32_spi_trans(0x0);
neorv32_spi_trans(0x0);
	// READ
neorv32_spi_trans(0x0);
neorv32_spi_trans(0x0);

neorv32_spi_cs_dis(0);  // lines are HIGH when deactivated.	
```

Analog Devices writes following related to SPI:

| SPI Mode  | CPOL  | CPHA  | Clock Polarity in Idle State  | Clock Phase Used to Sample and/or Shift the Data                      |
| --------- | ----- | ----- | ----------------------------- | --------------------------------------------------------------------- |
| 0         | 0     | 0     | Logic low                     | Data sampled on rising edge and shifted out on the falling edge       |
| 1         | 0     | 1     | Logic low                     | Data sampled on the falling edge and shifted out on the rising edge   |
| 2         | 1     | 0     | Logic high                    | Data sampled on the rising edge and shifted out on the falling edge   |
| 3         | 1     | 1     | Logic high                    | Data sampled on the falling edge and shifted out on the rising edge   |

*Table 1, https://www.analog.com/en/analog-dialogue/articles/introduction-to-spi-interface.html*

In my sim is the sreg updated on the falling edge of SCK:
![image](https://user-images.githubusercontent.com/106740887/179795741-e04ad7ce-92a5-4332-b641-0efff7172147.png)

In my opinion violates the SPI the Mode 0 spec. What do you think? As workaround could be two sreg used, one for RX, the other for TX to achieve the half SCK periode between update and capture.

Thanks for your comments.
BR, Andreas

**Comment by stnolting** [comment]
Oh, those relentless clock modes! 😅

> Analog Devices writes following related to SPI:

That is absolutely correct and matches the SPI clock modes described by this image:
![SPI_timing_diagram2 wikimedia](https://user-images.githubusercontent.com/22944758/179814081-f23f81ca-b98c-40c9-bc14-d1ed0337bf4a.png)

And this is also what "should" be implemented by the NEORV32 SPI and XIP modules.

> In my opinion violates the SPI the Mode 0 spec. What do you think?

Well, this is a complex situation since the SPI clock is quite close to the processor clock (_high-speed mode_ enabled). The actual sampling of the SDI signal takes places half a SPI clock cycle before the shift register is updated. This is what `rtx_engine.sdi_sync` is used for - to sample the SDI line before updating the shift register.

![spi](https://user-images.githubusercontent.com/22944758/179814862-cbe1116c-4c2d-4a98-9a91-68d2e4d96d40.png)

Have a look at this example transmission:
* sending/receiving `0x83` in 8-bit mode, SPI clock mode 0, high-speed mode enabled
* output data (`spi_sdo_o`) is updated at the falling edge of `spi_sck_o` ✔️
* input data (`spi_sdi_i`) is sampled at the rising edge of `spi_sck_o` into `rtx_engine.sdi_sync` (at the yellow cursor) ✔️

So I think the behavior is correct?! 🤔

**Comment by andkae** [comment]
Hi Stephan,

the thing with the 'rtx_engine.sdi_sync' is a real nice trick to safe a lot of FFs.

> So I think the behavior is correct?!

Absolutly. Thanks for the additional sims.


BR,
Andreas
