### ISSUE TITLE
dCache Docs

### ISSUE THREAD

**Issue by vhdlnerd** [stnolting/neorv32#564]
Its great the dCache was added! A few things:
1. A couple typos in the dCache docs (section 2.7.5).  `likt` should be `like` and `257 MB` should be `256 MB`
2. It would be helpful in the docs, section 2.6 Address Space, if the memory map figure showed which region is data cacheable.

**Comment by vhdlnerd** [comment]
I fixed the two typos in PR: #565

**Comment by stnolting** [comment]
> Its great the dCache was added! A few things:

Haha thanks! But it is still quite basic and not very performance-boosting 😉

> A couple typos in the dCache docs (section 2.7.5). likt should be like and 257 MB should be 256 MB

Thanks for finding (and fixing)!

> It would be helpful in the docs, section 2.6 Address Space, if the memory map figure showed which region is data cacheable.

I agree. I haven't done this yet because I am still thinking about a more generic mapping option. Maybe some programmable boundaries so you can define which addresses are cached and which are not?! 🤔

**Comment by stnolting** [comment]
> It would be helpful in the docs, section 2.6 Address Space, if the memory map figure showed which region is data cacheable.

What do you think about this?

![address_space](https://user-images.githubusercontent.com/22944758/232196759-41bf2bd5-7884-4745-bb37-c4fe5b4063ed.png)

**Comment by vhdlnerd** [comment]
Looks great to me!
